### ISSUE TITLE
Home assistant dashboard

### ISSUE THREAD

**Issue by NielsG24** [unii-security/homeassistant-unii#5]
Goedemiddag,

Ik heb mijn unii gekoppeld aan home assistant echt fijn dat deze intergratie er is bedankt hiervoor :) nu vraag ik mij af of het mogelijk is om deze te kunnen gebruiken met een alarm kaart voor op een Dashboard ?

**Comment by Jeroen-Alphatronics** [comment]
We hebben ervoor gekozen de alarmkaart op dit moment niet te implementeren omdat deze niet goed aansluit bij de structuur van de UNii. De alarmkaart gaat uit van deel/heel schakelingen en de UNii is gebaseerd op het schakelen van secties.
