### ISSUE TITLE
Synchronisatie werkt maar status komt niet binnen

### ISSUE THREAD

**Issue by deceijser** [unii-security/homeassistant-unii#7]
Besloten om over te gaan om de ML te vervangen voor een Unii i.v.m. de integratie naar Home Assistant.
Het doel is om uiteindelijk bij inschakeling een aanwezigheidssimulatie te starten zodat het lijkt alsof iemand thuis is.

Integratie is tot stand gebracht en ik heb een speciale gebruiker aangemaakt voor de Unii.
Ook dit werkt want de gebieden zijn in en uit te schakelen.

Helaas ontvang ik geen correcte status updates vanuit de Unii naar mijn Home Assistant server.
Zones blijven continue op gesloten staan en gebieden blijven uitgeschakeld.

Zie onderstaande screenshots.

![image](https://github.com/user-attachments/assets/99fa1b23-c9aa-431b-90c5-5eec4456380d)

![image](https://github.com/user-attachments/assets/4809a509-e758-444d-baa1-7250e132725c)

**Comment by AlphatronicsDev** [comment]
Voor de juiste werking van de koppeling tussen de UNii en Homeassistant dient de UNii minimaal firmware versie 2.17.0  te hebben. 

Daarnaast moet de API in de UNii als volgt ingesteld worden:
Transmissie: TCP
Ingang update interval  op 0 
API versie: UNii

Mocht het probleem hiermee niet opgelost zijn dan kan uw installateur contact op nemen met onze support afdeling.

**Comment by deceijser** [comment]
Dank voor het antwoord, er was inderdaad een update volgens UNii online, helaas kwam deze niet naar voren in de manager software.
Het werkt nu naar behoren.
